"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Saturn.py']
DATA_FILES = [('', ['model']), "voice.mp3", "wikipedia-iso-country-codes.csv"]
OPTIONS = {
    "iconfile":"icon.icns"
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
